# Generated by Django 5.1.5 on 2025-01-23 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=8)),
                ("email", models.CharField(max_length=50)),
                ("contact", models.CharField(max_length=10)),
                ("image", models.ImageField(blank=True, upload_to="media")),
                ("status", models.IntegerField(default=1)),
                ("role", models.CharField(default="user", max_length=50)),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=50)),
                ("status", models.IntegerField(default=0)),
                ("email", models.CharField(default="xyz", max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myApp.user"
                    ),
                ),
            ],
            options={
                "db_table": "message",
            },
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.FloatField()),
                ("category", models.CharField(max_length=50)),
                ("remark", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myApp.user"
                    ),
                ),
            ],
            options={
                "db_table": "income",
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.FloatField()),
                ("category", models.CharField(max_length=50)),
                ("remark", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myApp.user"
                    ),
                ),
            ],
            options={
                "db_table": "expense",
            },
        ),
    ]
